steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci']

  # Build frontend with backend URL
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      - 'VITE_API_URL=${_BACKEND_URL}'
  
  # Replace Maps API key in index.html
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i "s/YOUR_GOOGLE_MAPS_API_KEY/$$MAPS_API_KEY/g" dist/index.html
    secretEnv: ['MAPS_API_KEY']

  # Deploy to Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '-d'
      - 'dist/'
      - 'gs://${_BUCKET_NAME}/'

  # Set cache control for static assets
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'setmeta'
      - '-h'
      - 'Cache-Control:public, max-age=31536000'
      - 'gs://${_BUCKET_NAME}/assets/**'

  # Set cache control for HTML (no cache)
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - 'setmeta'
      - '-h'
      - 'Cache-Control:no-cache, no-store, must-revalidate'
      - 'gs://${_BUCKET_NAME}/index.html'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/MAPS_API_KEY/versions/latest
      env: 'MAPS_API_KEY'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _BUCKET_NAME: 'contractorv3-frontend'
  _BACKEND_URL: 'https://contractorv3-backend-xxx.run.app'

timeout: '600s'
