steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci']

  # Inject Maps API key into index.html before build
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'sed -i "s|\$MAPS_API_KEY|$$MAPS_API_KEY|g" index.html'
    secretEnv: ['MAPS_API_KEY']

  # Build frontend with backend URL
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      - 'VITE_API_URL=${_BACKEND_URL}'
      - 'VITE_GOOGLE_MAPS_API_KEY=$$MAPS_API_KEY'
    secretEnv: ['MAPS_API_KEY']

  # Deploy to Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '-d'
      - 'dist/'
      - 'gs://${_BUCKET_NAME}/'



availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/MAPS_API_KEY/versions/latest
      env: 'MAPS_API_KEY'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _BUCKET_NAME: 'contractorv3-frontend'
  _BACKEND_URL: 'https://contractorv3-backend-291626603758.us-central1.run.app/api'

timeout: '600s'
