steps:
  # Build Docker image with build args
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --build-arg VITE_MAPS_API_KEY=$$MAPS_API_KEY \
          -t gcr.io/$PROJECT_ID/contractor-crm-v2:$COMMIT_SHA \
          -t gcr.io/$PROJECT_ID/contractor-crm-v2:latest \
          .
    secretEnv: ['MAPS_API_KEY']
  
  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/contractor-crm-v2:$COMMIT_SHA']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/contractor-crm-v2:latest']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'backend'
      - '--image=gcr.io/$PROJECT_ID/contractor-crm-v2:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=${_CLOUDSQL_INSTANCE}'
      - '--set-env-vars=NODE_ENV=production,PORT=8080,DATABASE_URL=${_DATABASE_URL},JWT_SECRET=${_JWT_SECRET}'
      - '--set-secrets=GEMINI_API_KEY=GEMINI_API_KEY:latest,TAVILY_API_KEY=TAVILY_API_KEY:latest,MAPS_API_KEY=MAPS_API_KEY:latest'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--timeout=300'
      - '--port=8080'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/MAPS_API_KEY/versions/latest
      env: 'MAPS_API_KEY'

images:
  - 'gcr.io/$PROJECT_ID/contractor-crm-v2:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/contractor-crm-v2:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: 'us-central1'
  _CLOUDSQL_INSTANCE: 'YOUR_PROJECT_ID:us-central1:YOUR_INSTANCE_NAME'
  _DATABASE_URL: 'YOUR_DATABASE_URL_FROM_SECRET_MANAGER'
  _JWT_SECRET: 'YOUR_JWT_SECRET_FROM_SECRET_MANAGER'

timeout: '1200s'
